server:
  port: 8084
  forward-headers-strategy: framework

spring:
  application:
    name: section-service
  
  config:
    import:
      - optional:configserver:http://localhost:8888
      - optional:file:../.env
  
  datasource:
    url: jdbc:mysql://${SECTION_DB_HOST:localhost}:${SECTION_DB_PORT:3306}/${SECTION_DB_NAME:airesume_section}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
    username: ${SECTION_DB_USERNAME:root}
    password: ${SECTION_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
  # Redis Caching
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    hostname: localhost
    non-secure-port: 8084
    instance-id: ${spring.application.name}:${server.port}
    appname: SECTION-SERVICE

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    custom-css-url: /swagger-custom.css
  api-docs:
    path: /v3/api-docs

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:86400000}
