server:
  port: 8084

spring:
  application:
    name: section-service
  
  config:
    import: optional:configserver:http://localhost:8888
  
  datasource:
    url: jdbc:mysql://${SECTION_DB_HOST:localhost}:3306/${SECTION_DB_NAME:airesume_section}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
    username: ${AUTH_DB_USERNAME:root}
    password: ${AUTH_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        
  # Redis Caching
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
