package com.airesume.sectionservice.model;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;

/**
 * JPA Entity representing a Resume Section.
 * Stores content (as JSON string), display order, and AI metadata.
 */
@Entity
@Table(name = "resume_sections")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Section {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long sectionId;

    @Column(nullable = false)
    private Long resumeId;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private SectionType sectionType;

    @Column(nullable = false)
    private String title;

    /**
     * Stores the actual content of the section.
     * Content is stored as a JSON string to accommodate different section structures.
     */
    @Lob
    @Column(columnDefinition = "LONGTEXT")
    private String content;

    /**
     * Order in which the section appears in the resume.
     */
    @Column(nullable = false)
    private Integer displayOrder;

    /**
     * Flag to toggle section visibility in the final resume.
     */
    @Builder.Default
    private Boolean isVisible = true;

    /**
     * Flag indicating if the content was generated by AI.
     */
    @Builder.Default
    private Boolean aiGenerated = false;

    @CreationTimestamp
    private LocalDateTime createdAt;

    @UpdateTimestamp
    private LocalDateTime updatedAt;
}
