server:
  port: 9090

spring:
  application:
    name: ADMIN-SERVER
  config:
    import: optional:file:../.env
  security:
    user:
      name: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
    appname: ADMIN-SERVER

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
